name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci
        id: dependencies

      - name: Lint
        run: nr lint
        if: steps.dependencies.outcome == 'success'

      - name: Typecheck
        run: nr typecheck
        if: steps.dependencies.outcome == 'success'

      - name: Test
        run: nr test
        if: steps.dependencies.outcome == 'success'

      - name: Build
        run: nr build
        if: steps.dependencies.outcome == 'success'
